name: PR Handler

on:
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  handle-pull-request:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Info
        shell: bash
        run: |
          echo 'Repo: ${{ github.repository }}'
          echo 'User: ${{ github.actor }}'
          echo "Base ref: ${{ github.base_ref }}"
          echo "$(gh api /repos/${{ github.repository }} --jq '.default_branch')"
          
      #- name: Run a one-line script
      #  run: echo "Hello API $(gh api /repos/${{ github.repository }}/branches/{{ github.actor }} --silent')"

      - name: Create branch if not exists
        run: |
          if ! gh api repos/${{ github.repository }}/branches/${{ github.actor }} --silent;
          then
            gh api --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            repos/${{ github.repository }}/git/refs \
            -f ref='refs/heads/${{ github.actor }}' \
            -f sha="$(gh api repos/${{ github.repository }}/git/ref/heads/main -q '.. | .sha? | select(. != null)')"
          else
            echo "Branch ${{ github.actor }} already exists"
          fi
        

